- Gouvernance.md
- Instanciation.md
- Introduction.md
- Ouverture.md
- Pratique.md
Quelques retouches typographiques.
> Typographie

- MAINTAINERS
- README.md
- introduction.md
- ouverture.md
- pratique.md
Pas d'intervention sur le fond, uniquement de l'orthographe et de la typo
> Relecture ortho typo

- pratique.md
Voir https://github.com/DISIC/politique-de-contribution-open-source/issues/38#issuecomment-353606098
> Précision sur la notion de « nom de domaine professionnel »

- index.html
Je n'ai pas trouvé la source de ce fichier désolé :)
> MAJ date limite au 28 Janvier 2018

- faq.md
- ouverture.md
- pratique.md
> Contributions suite aux discussions IRL

- introduction.md
j'ai revu un peu la formulation
> document en beta

- faq.md
Ajout de sections
Réponse pour compte d'organisation absent
> Ajout de sections

- MAINTAINERS
- faq.md
- gouvernance.md
- introduction.md
- ouverture.md
- pratique.md
Les suggestions sont maintenant effectuées sur la branche next. 
Les modifications et discussions sont faites sur next
La PR de next vers master détermine l'update de version MAJEUR ou MINEUR, et un vote est demandé en fonction selon les règles de la gouvernance.
L'HTML est généré à partir de master
> Synchronisation de next avec master

- faq.en.md
- instanciation.en.md
- introduction.en.md
- ouverture.en.md
- pratique.en.md
Salut, j'ai relevé quelques coquilles dans les versions anglaises des pages. Rien de bien grave. Bravo pour le boulot, très heureux d'être citoyen d'un pays qui essaye d'être aussi ouvert !
> Fixed a few typos

- pratique.md
Petite typo repérée, sinon beau travail!
> Correction du lien (reuse.software)

- OrgAccounts
IGNF = Institut National de l'Information Géographique et Forestière
> Adding IGNF repos

- OrgAccounts
> ajout de l'observatoire des territoires

- pratique.en.md
- pratique.md
See https://github.com/DISIC/politique-de-contribution-open-source/issues/88
> Add a recommendation on organization accounts' owners

- pratique.md
Quelques corrections mineures sur la page pratique.
> Corrections orthographiques page pratique

- DCO-fr.txt
Voir https://github.com/DISIC/politique-de-contribution-open-source/issues/64
> Traduction plus littérale pour le DCO

- pratique.md
Voir https://github.com/DISIC/politique-de-contribution-open-source/issues/46
> Ajout d'une section sur les bonnes pratiques de documentation

- MAINTAINERS
- gouvernance.en.md
- gouvernance.md
Voir https://github.com/DISIC/politique-de-contribution-open-source/issues/132
> Précision sur la validation des pull requests

- comptes-organismes-publics
LEIA est un projet développé à l'ANSSI (dérivé de WooKey)
> Ajout projet LEIA

- comptes-organismes-publics
> Remove duplicate

- comptes-organismes-publics
OpenCTI est un outil de cyber-threat intelligence management, nouvellement annoncé par l'ANSSI (https://www.ssi.gouv.fr/actualite/opencti-la-solution-libre-pour-traiter-et-partager-la-connaissance-de-la-cybermenace/)
> Ajout organisation OpenCTI-Platform

- comptes-organismes-publics
Répare l'erreur d'ajout dans #164
> Suppression faux compte Legifrance

- comptes-organismes-publics
> Ajout GitHub Ministères économiques et financiers

- comptes-organismes-publics
Entrepôt de Données de Santé - French Healthcare Data Warehouse - APHP
> ajout EDS-APHP

- comptes-organismes-publics
Compte de l'agence française pour la biodiversité
> Ajout de AFB Data viz

- comptes-organismes-publics
> Add Ifsttar Github account

- comptes-organismes-publics
ISTEX organisation contains repositories of some parts of ISTEX platform. (demo website, widgets, harvester, istex-downloader...)
ISTEX is a french platform which aims to store scientific publications and give access to french research higher education.
More than 23.000.000 scientific papers are available for download. Granted users can access to it for reading but also for text-mining purpose.
> add ISTEX repositories to public organisations list

- comptes-organismes-publics
> update with gitlab.inria.fr

- comptes-organismes-publics
LexImpact is a project developed by Assemblée nationale. I guess this is eligible
> Add new account

- comptes-organismes-publics
Add acount of IRSN which is a public service https://lannuaire.service-public.fr/gouvernement/etablissement-public_172080
> Add account of IRSN
