DISIC/politique-de-contribution-open-source

instanciation.md, pratique.md
Dans le texte, des guillemets droits sont utilisés à la place des guillemets français. Ce commit corrige les deux cas qui se présentent.
Je me demande cependant si l'usage des guillemets est justifié dans les deux cas. Dans le cas « Bill of rights », il me semble que l'italique devrait être préférée (on nomme un ouvrage, ce n'est pas une citation). De même pour le cas « politique « mère » », il ne s'agit pas d'une citation.
=> Utilisation des guillemets français

LICENSE
revue ortho-typo : 
- les majuscules doivent être accentuées
- format markdown plus strict (titres, espace après un paragraphe)
Je proposerais également de ne pas écrire les titres en majuscules.
Faudrait peut-être aussi unifier le format des listes : "*" ou "-" ?
=> typo : majuscules doivent être accentuées et revue markdown

pratique.md
La traduction consacrée de "Best practices" est plutôt "Bonnes pratiques" que "Meilleures pratiques"
=> Correction du titre : Bonnes pratiques

pratique.md
Dans le contexte du paragraphe, la formule « l'administration qui peut
disposer également de sa propre forge publique » me paraît flou.  Dire
« héberger sa propre forge publique » est plus clair, souligne le fait
qu'il y a un hébergement, de la maintenance, etc.
À titre personnel, je suis *pour* mettre en avant la possibilité, pour
les administrations, d'héberger leur plateforme de collaboration ainsi
que les outils qui le permettent (Gitlab CE, gogs.io, gitea.io, etc.)
Je ne suis pas convaincu qu'il sera plus difficile de suivre tous les
dépôts publics s'ils sont hébergés sur des plateformes distinctes.  Je
pense au contraire que le fait d'avoir plein de dépôts publics sur
github.com, gitlab.com etc. fera que pour centraliser la liste de ces
dépôts, il faudra une liste des comptes …
=> Clarification sur l'hébergement d'une forge

DCO-fr.txt, faq.md, pratique.md
Le titre précédent (« Aide au choix d'une plateforme Web ») donne
l'impression que la décision de publier sur telle ou telle plateforme
revient aux développeurs (car le document s'adresse au développeurs),
alors qu'elle revient aux administrations.  Le titre proposé est plus
neutre.
Je propose aussi de retirer la mention disant que github.com rassemble
la plus grande communauté de développeurs, qui donne aussi l'impression
que le document recommande d'utiliser github.com, alors qu'une telle
recommandation vise l'administration, pas les développeurs.
=> Clarification du titre et retrait de la mention sur github.com

pratique.md
Suppression des consignes trop précises.
Avertissement contre la sécurité par l'obscurité
Ajout des questions de propriété intellectuelle pour l'interlocuteur de référence
=> Reformulation partie Sécurité

faq.md, introduction.md, pratique.md
Quelques corrections typo et ajout du code pour permettre de rendre pliable / dépliable les questions de premier niveau de la faq.
=> corrections typo et faq dépliable 

OrgAccounts
Opendatateam is the repo where Etalab publish code for udata.
=> add opendatateam

OrgAccounts
SNOSAN : Observatoire accidentologie plaisance et loisirs nautiques France
=> Ajout du SNOSAN

OrgAccounts
Ajout de quatre organisations du Commissariat à l’énergie atomique et aux énergies alternatives (CEA) sur Github:
- cea-hpc: calcul haute performance
- cea-leti: institut LETI
- cea-list: institut LIST
- cea-sec: sécurité des systèmes d'information
=> Ajout du CEA

introduction.en.md, introduction.md, ouverture.en.md, ouverture.md, pratique.en.md, pratique.md
Voir ce [ticket](https://github.com/DISIC/politique-de-contribution-open-source/issues/104).
Le but est de rendre cliquables les liens sur https://www.numerique.gouv.fr/publications/politique-logiciel-libre/
=> Mise en liens des urls brutes

MAINTAINERS, pratique.en.md, pratique.md
- Recommandation sur la visibilité des noms d'utilisateur des comptes d'organisation
- Suppression de mchoquet de la liste des mainteneurs DINSIC
=> Corrections marginales

gouvernance.en.md, gouvernance.md
Le lien vers la page MAINTAINERS est rompu lors de la publication sur https://www.numerique.gouv.fr/publications/politique-logiciel-libre/gouvernance/ comme le chemin est relatif.
Cette PR remplace le lien par un lien complet
=> Lien cassé vers MAINTAINERS

comptes-organismes-publics
Quelques comptes qui étaient répertoriés là-bas (https://github.com/github/government.github.com/blob/gh-pages/_data/governments.yml#L221) et non ici
=> Ajouts de comptes depuis government.github.com

comptes-organismes-publics
Projets numériques du musée Saint-Raymond, musée d'Archéologie de Toulouse.
=> Ajout du musée Saint-Raymond de Toulouse

comptes-organismes-publics
AFBDataviz est un compte utilisateur mais n'est pas un compte d'organisation
=> Retrait d'AFBdataviz

comptes-organismes-publics
SmartPLU n'est pas un compte organisation
Géographie cités est une UMR donc rentre dans le scope à mon avis
=> retrait SMART PLU et ajout Géographie cités

comptes-organismes-publics
Bonjour,
Ajout du compte Gitlab du PEReN (https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000042297154/).
Au passage, est-ce que les sous-projets Gitlab sont bien gérés par l'outil ?
Bonne journée,
=> Ajout compte Gitlab du PEReN

comptes-organismes-publics
Qui sommes-nous ? datagir.ademe.fr
Anciennement hébergé chez betagouv, nous commençons à avoir tellement de dépôts qu'on ne s'y retrouve plus, et le préfixe datagir-mondépôt devenait systématique.
=> Ajout de datagir

comptes-organismes-publics
New account for DG Tresor (https://lannuaire.service-public.fr/gouvernement/administration-centrale-ou-ministere_171762).
=> New Framagit's account for DG Tresor
